# Generated by Django 5.2.11 on 2026-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('compras', 'Compras'), ('analista', 'Analista'), ('proveedor', 'Proveedor')], max_length=20),
        ),
    ]
