# Generated by Django 5.2.11 on 2026-03-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_remove_compra_total_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='precio_unitario',
        ),
    ]
