# Generated by Django 5.2.11 on 2026-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_detallecompra_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id_estado',
            field=models.CharField(max_length=20),
        ),
    ]
